### ISSUE TITLE
"Your browser is not currently supported"

### ISSUE THREAD

**Issue by SRZIsHere** [Nyxqxx/Twitch-Account-Creator#18]
(I Disabled the clicking at the End of the script that doesn't works (=commented lines 127 to 133))

And when I press "Sign Up" after the date of birth, it says :

"Your browser is not currently supported." (And If i use my installed browser normally (Firefox 114) and manually create an account everything works fine ...

**Comment by Nyxqxx** [comment]
This error is caused by the program triggering twitch's new bot detection system. Currently the only potential fix is to increase the timings significantly.

**Comment by SRZIsHere** [comment]
And how ?

**Comment by Nyxqxx** [comment]
https://www.browserstack.com/guide/python-selenium-to-run-web-automation-test
https://realpython.com/python-sleep/

**Comment by T3los** [comment]
Any up on this ? I tried with delay between each action and i still got the error, using firefox 
```
Your browser is not currently supported. Please use a [recommended browser](https://help.twitch.tv/s/article/supported-browsers) or learn more [here](https://help.twitch.tv/s/article/supported-browsers).
```
