### ISSUE TITLE
No module named fake_useragent

### ISSUE THREAD

**Issue by Astracheatsdev** [Nyxqxx/Twitch-Account-Creator#19]
Title says it

**Comment by Nyxqxx** [comment]
'''
pip install fake_username
'''

**Comment by Astracheatsdev** [comment]
"Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement fake_username (from versions: none)
ERROR: No matching distribution found for fake_username"
